"use client";

import { ChevronDown } from "lucide-react";
import { useState, type ReactNode } from "react";
import { WarehousePanel } from "./warehouse-panel";

function Field({ label, helper, children, marker }: { label: string; helper: string; children: ReactNode; marker?: string }) { return <label className="block"><span className="mb-2 flex items-center justify-between text-xs font-medium uppercase tracking-wide"><span>{label}</span>{marker && <span className="font-mono text-[10px] normal-case tracking-normal text-muted-foreground">{marker}</span>}</span>{children}<span className="mt-2 block text-xs leading-5 text-muted-foreground">{helper}</span></label>; }
const checks = [["Scannable Zone", "Valid for RF handhelds", true], ["Auto-Putaway", "Target for inbound POs", true], ["Restricted Access", "Requires Tier-2 badge", false]] as const;

export function LocationProfile() {
  const [toggles, setToggles] = useState(checks.map(([, , enabled]) => enabled));
  return <WarehousePanel className="p-5 sm:p-6"><div className="flex flex-col gap-3 border-b border-border pb-5 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-base font-semibold">Location Profile</h2><p className="mt-1 text-sm text-muted-foreground">General identity parameters matching ERP ledger routing specifications.</p></div><span className="w-fit rounded border border-border bg-secondary px-2 py-1 font-mono text-xs text-muted-foreground">Internal Storage Node</span></div><div className="grid gap-x-5 gap-y-6 py-6 md:grid-cols-2"><Field label="Name" marker="required" helper="Descriptive human-readable name of the facility sector."><input defaultValue="Stock 1 - Inflow & Pallet Racks" className="h-9 w-full rounded-md border border-input bg-card px-3 text-sm outline-none ring-primary-500/40 focus:ring-2" /></Field><Field label="Short code" marker="wireframe: stock1" helper="Unique location identifier used on bin labels and picking slips."><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">#</span><input defaultValue="WH/Stock1" className="h-9 w-full rounded-md border border-input bg-card pl-7 pr-3 font-mono text-sm outline-none ring-primary-500/40 focus:ring-2" /></div></Field><Field label="Warehouse" marker="linked via WH" helper="Parent storage warehouse establishing physical address bounds."><div className="relative"><select defaultValue="WH — Main Central Logistics Hub" className="h-9 w-full appearance-none rounded-md border border-input bg-card px-3 text-sm outline-none ring-primary-500/40 focus:ring-2"><option>WH — Main Central Logistics Hub</option><option>WH2 — East Dispatch Hub</option></select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /></div></Field><Field label="Location type" helper="Governs inventory reservation algorithms and automated replenishment passes."><div className="relative"><select defaultValue="Internal Storage (Rack & Shelves)" className="h-9 w-full appearance-none rounded-md border border-input bg-card px-3 text-sm outline-none ring-primary-500/40 focus:ring-2"><option>Internal Storage (Rack & Shelves)</option><option>Staging Area</option><option>Climate Controlled</option></select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /></div></Field></div><div className="grid gap-4 border-t border-border pt-5 sm:grid-cols-3">{checks.map(([label, helper], index) => <label key={label} className="flex cursor-pointer items-start gap-2.5"><input type="checkbox" checked={toggles[index]} onChange={() => setToggles((state) => state.map((value, i) => i === index ? !value : value))} className="mt-1 size-4 accent-primary" /><span><span className="block text-sm font-medium">{label}</span><span className="mt-1 block text-xs text-muted-foreground">{helper}</span></span></label>)}</div></WarehousePanel>;
}
